
<h2><?php echo $this->purify($this->translate('Koryukan Dojo')); ?></h2>

<table border=2 bordercolordark='#FAEDDA' style='width:550px' cellpadding=5>
    <tr>
        <td colspan=2 align='center'>
            <?php echo $this->purify($this->translate('Gym Zone, 8351 Newman Boulevard')); ?><br>
            <?php echo $this->purify($this->translate('LaSalle Quebec')); ?> <br>
            (514) 827-9945 <br>
            (514) 250-8207 <br />
            Email: <a href='mailto:info@koryukan.com'>info@koryukan.com</a><br>
            Email: <a href='mailto:enfants@koryukan.com'>enfants@koryukan.com</a><br>
        </td>
    </tr>
    <tr>
        <td colspan=2 align='center'><strong><?php echo $this->purify($this->translate('Class Times')); ?>: </strong><br>
            <strong><?php echo $this->purify($this->translate('Adult')); ?>:</strong> <br>
            <strong><?php echo $this->purify($this->translate('Mondays and Wednesdays')); ?></strong> <br>
            <?php echo $this->purify($this->translate('8:00 PM to 10:00 PM')); ?><br>
            <strong><?php echo $this->purify($this->translate('Sunday')); ?></strong><br />
            <?php echo $this->purify($this->translate('11:00 AM to 12:30 AM')); ?><br /><br />
            <strong><?php echo $this->purify($this->translate('Children-Family')); ?>:</strong> <br>
            <strong><?php echo $this->purify($this->translate('Sunday')); ?></strong> <br>
            <?php echo $this->purify($this->translate('10:00 AM to 11:00 AM')); ?>
        </td>
    </tr>
    <tr>
        <td>
            <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=<?php echo $this->mapLanguage; ?>&amp;geocode=&amp;q=8351+Boulevard+Newman,+LaSalle,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H8N+1Y4,+Canada&amp;sll=45.433086,-73.629647&amp;sspn=0.002989,0.006968&amp;ie=UTF8&amp;hq=&amp;hnear=8351+Boulevard+Newman,+LaSalle,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H8N+1Y4,+Canada&amp;z=14&amp;ll=45.432796,-73.629617&amp;output=embed"></iframe>
            <br />
            <small>
                <a target='_blank' href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=<?php echo $this->mapLanguage; ?>&amp;geocode=&amp;q=8351+Boulevard+Newman,+LaSalle,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H8N+1Y4,+Canada&amp;sll=45.433086,-73.629647&amp;sspn=0.002989,0.006968&amp;ie=UTF8&amp;hq=&amp;hnear=8351+Boulevard+Newman,+LaSalle,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H8N+1Y4,+Canada&amp;z=14&amp;ll=45.432796,-73.629617" style="color:#0000FF;text-align:left">
                    <?php echo $this->purify($this->translate('View Larger Map')); ?>
                </a>
            </small>
        </td>
    </tr>
</table>




<br />
<h2><?php echo $this->purify($this->translate('Dokyoo Dojo')); ?></h2>
<table border=2 bordercolordark='#FAEDDA' style='width:550px' cellpadding=5>
    <tr>
        <td colspan=2 align='center'>
            <?php echo $this->purify($this->translate('Sainte-Sophie Orthodox Ukrainian Cathedral,')); ?><br />
<!--            <?php echo $this->purify($this->translate('6250 12 i&egrave;me avenue')); ?><br />  -->
            <?php echo $this->purify($this->translate('Montr&eacute;al, QC')); ?> <br />
            <?php echo $this->purify($this->translate('H1X 3A5')); ?><br />
            Email: <a href='mailto:info@koryukan.com'>info@koryukan.com</a><br>
        </td>
    </tr>
    <tr>
        <td colspan=2 align='center'>
            <strong><?php echo $this->purify($this->translate('Class Times')); ?>:</strong><br>
            <strong><?php echo $this->purify($this->translate('Sunday')); ?></strong> <br>
            <?php echo $this->purify($this->translate('03:00 PM to 04:30 PM')); ?>
        </td>
    </tr>
<!--
    <tr>
        <td>
            <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=<?php echo $this->mapLanguage; ?>&amp;geocode=&amp;q=6250+12e+avenue+montreal&amp;sll=37.09024,-95.712891&amp;sspn=54.621153,114.169922&amp;ie=UTF8&amp;hq=&amp;hnear=6250+12+Av,+Montr%C3%A9al,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H1X+3M9,+Canada&amp;z=14&amp;ll=45.554642,-73.581992&amp;output=embed"></iframe>
            <br />
                <small>
                    <a target='_blank' href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=<?php echo $this->mapLanguage; ?>&amp;geocode=&amp;q=6250+12e+avenue+montreal&amp;sll=37.09024,-95.712891&amp;sspn=54.621153,114.169922&amp;ie=UTF8&amp;hq=&amp;hnear=6250+12+Av,+Montr%C3%A9al,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H1X+3M9,+Canada&amp;z=14&amp;ll=45.554642,-73.581992" style="color:#0000FF;text-align:left">
                        <?php echo $this->purify($this->translate('View Larger Map')); ?>
                    </a>
                </small>
        </td>
    </tr>
-->
</table>


<br />
<h2><?php echo $this->purify($this->translate("Sainte-Anne's Dojo")); ?></h2>
<table border=2 bordercolordark='#FAEDDA' style='width:550px' cellpadding=5>
    <tr>
        <td colspan=2 align='center'>
            <?php echo $this->purify($this->translate('Chalet Peter Williamson, Parc Aumais')); ?><br />
            <?php echo $this->purify($this->translate('300, Cypihot street,')); ?><br />
            <?php echo $this->purify($this->translate('Sainte-Anne-de-Bellevue, QC')); ?> <br />
            Email: <a href='mailto:info@koryukan.com'>info@koryukan.com</a><br>
        </td>
    </tr>
    <tr>
        <td colspan=2 align='center'>
            <strong><?php echo $this->purify($this->translate('Class Times')); ?>:</strong><br />
            <strong><?php echo $this->purify($this->translate('Friday')); ?></strong> <br />
            <?php echo $this->purify($this->translate('06:30 PM to 08:00 PM')); ?><br />

            <strong><?php echo $this->purify($this->translate('Sunday')); ?></strong><br />
            <?php echo $this->purify($this->translate('11:15 AM to 12:45 PM')); ?><br /><br />
        </td>
    </tr>
    <tr>
        <td>
            <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=<?php echo $this->mapLanguage; ?>&amp;geocode=&amp;q=300,+rue+Cypihot,+Sainte-Anne-de-Bellevue&amp;sll=45.438698,-73.927833&amp;sspn=0.002989,0.006968&amp;ie=UTF8&amp;hq=&amp;hnear=300+Rue+Cypihot,+Sainte-Ann-De-Bellevue,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H9X+4A8,+Canada&amp;z=14&amp;ll=45.439383,-73.927393&amp;output=embed"></iframe>
            <br />
            <small>
                <a target='_blank' href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=<?php echo $this->mapLanguage; ?>&amp;geocode=&amp;q=300,+rue+Cypihot,+Sainte-Anne-de-Bellevue&amp;sll=45.438698,-73.927833&amp;sspn=0.002989,0.006968&amp;ie=UTF8&amp;hq=&amp;hnear=300+Rue+Cypihot,+Sainte-Ann-De-Bellevue,+Communaut%C3%A9-Urbaine-de-Montr%C3%A9al,+Qu%C3%A9bec+H9X+4A8,+Canada&amp;z=14&amp;ll=45.439383,-73.927393" style="color:#0000FF;text-align:left">
                    <?php echo $this->purify($this->translate('View Larger Map')); ?>
                </a>
            </small>
        </td>
    </tr>
</table>