
<h2><?php echo $this->purify($this->translate('Koryukan Dojo')); ?></h2>

<table border=2 bordercolordark='#FAEDDA' style='width:550px' cellpadding=5>
    <tr>
        <td colspan=2 align='center'>
            <?php echo $this->purify($this->translate('Gym Zone, 8351 Newman Boulevard')); ?><br>
            <?php echo $this->purify($this->translate('LaSalle Quebec')); ?> <br>
            (514) 827-9945 <br>
            (514) 250-8207 <br />
            Email: <a href='mailto:info@koryukan.com'>info@koryukan.com</a><br>
            Email: <a href='mailto:enfants@koryukan.com'>enfants@koryukan.com</a><br>
        </td>
    </tr>
    <tr>
        <td colspan=2 align='center'><strong><?php echo $this->purify($this->translate('Class Times:')); ?></strong><br>
            <strong><?php echo $this->purify($this->translate('Adult')); ?>:</strong> <br>
            <strong><?php echo $this->purify($this->translate('Mondays and Wednesdays')); ?></strong> <br>
            <?php echo $this->purify($this->translate('8:00 PM to 10:00 PM')); ?><br>
            <strong><?php echo $this->purify($this->translate('Sunday')); ?></strong><br />
            <?php echo $this->purify($this->translate('11:00 AM to 12:30 AM')); ?><br /><br />
            <strong><?php echo $this->purify($this->translate('Children-Family')); ?>:</strong> <br>
            <strong><?php echo $this->purify($this->translate('Sunday')); ?></strong> <br>
            <?php echo $this->purify($this->translate('10:00 AM to 11:00 AM')); ?>
        </td>
    </tr>
</table>


<br />
<h2><?php echo $this->purify($this->translate('Dokyoo Dojo')); ?></h2>
<table border=2 bordercolordark='#FAEDDA' style='width:550px' cellpadding=5>
    <tr>
        <td colspan=2 align='center'>
            <?php echo $this->purify($this->translate('Sainte-Sophie Orthodox Ukrainian Cathedral,')); ?><br />
            <?php echo $this->purify($this->translate('6250 12 i&egrave;me avenue')); ?><br />
            <?php echo $this->purify($this->translate('Montr&eacute;al, QC')); ?> <br />
            <?php echo $this->purify($this->translate('H1X 3A5')); ?><br />
            Email: <a href='mailto:info@koryukan.com'>info@koryukan.com</a><br>
        </td>
    </tr>
    <tr>
        <td colspan=2 align='center'>
            <strong><?php echo $this->purify($this->translate('Class Times')); ?>:</strong><br>
            <strong><?php echo $this->purify($this->translate('Sunday')); ?></strong> <br>
            <?php echo $this->purify($this->translate('03:00 PM to 04:30 PM')); ?>
        </td>
    </tr>
</table>