<?php
    $sidebarmenu =  $this->partial('partial/daitoryusubmenu.phtml', array('submenu' => $this->submenu));
    $this->placeholder('sidebarmenu')->set($sidebarmenu);
?>

<div id='daitoryucontent'>
    <h3><?php echo $this->purify($this->translate("THE HISTORY OF DAITO RYU AIKI JUJUTSU")); ?></h3>
    <p><em><?php echo $this->purify($this->translate("by")); ?> <a href='http://www3.sympatico.ca/iaido/soke.htm' target='new'>Dr. Robert Thivierge</a></em></p>

    <p><em><?php echo $this->purify($this->translate("Members of the Koryukan dojo would like to extend their gratitude to
       Dr. Thivierge for his unselfish contribution to our website. We are all
       better off for his generosity.")); ?></em></p>

    <p><?php echo $this->purify($this->translate("Aiki Jujutsu is a traditional Japanese combative discipline, the essence of the art is contained in the name.")); ?></p>

    <dl>
        <dt><?php echo $this->purify($this->translate("Ai")); ?></dt>
        <dd><?php echo $this->purify($this->translate("means to meet or harmony")); ?></dd>

        <dt><?php echo $this->purify($this->translate("Ki")); ?></dt>
        <dd><?php echo $this->purify($this->translate("is the life energy that animates all living things")); ?></dd>

        <dt><?php echo $this->purify($this->translate("Ju")); ?></dt>
        <dd><?php echo $this->purify($this->translate("means flexible or non resistant")); ?></dd>

        <dt><?php echo $this->purify($this->translate("Jutsu")); ?></dt>
        <dd><?php echo $this->purify($this->translate("means an art")); ?></dd>

    </dl>

    <p><?php echo $this->purify($this->translate("In Aiki jujutsu we discover an art with which we can master conflic by means of harmonizing with the life energy that animates the opponent. With this harmony it becomes possible to face the tests life continually sends our way.")); ?></p>

    <p><?php echo $this->purify($this->translate("The origin of Daito ryu aiki jujutsu can be traced to emperor Seiwa (850 A.D).")); ?></p>
    <p><?php echo $this->purify($this->translate("Long kept a secret under the Minamoto clan, the art was used by the Emperor's army and private guard. Controlled by Japanese nobility, appointed official martial art of the Shogun's residence by Hoshina Masayuki in the late 1600's, Daito techniques were transmitted from generation to generation.")); ?></p>
    <p><?php echo $this->purify($this->translate("Through the centuries numerous masters of this discipline were important war lords, such as Shingen Takeda, undoubtedly the most famous in Japanese culture. Among his collateral descendants, whose destinies were intimately linked with Daito ryu, we find Sokaku Takeda, a master and a reviver of the art.")); ?></p>

    <div class="clear"></div>

    <img src='/Images/History/MinamotoYoshimitsu.jpg' alt='Minamoto Yoshimitsu' />
    <p><strong>Minamoto Yoshimitsu</strong><?php echo $this->purify($this->translate("was the son of prince Minamoto Yoriyoshi (lord of Chinjuf). Direct descendants of Emperor Seiwa.")); ?></p>

    <p><?php echo $this->purify($this->translate("Emperor Seiwa was a lackluster leader as most japanese emperors were.
        Yoshimitsu inherited an art that had been developed by his forefathers
        and said to be related to Sumo; he perfected this discipline which was
        to be the roots of what is now known as Daito Ryu (Daito was the name
        of Yoshimitsu's summer residence). Legend has it that in creating new
        techniques he is said to have been influenced by observing the movements
        of a spider trapping its prey.")); ?></p>
    <p><?php echo $this->purify($this->translate("He was also known as an exceptional horseman and a master of kenjutsu,
        kyujutsu and sojutsu (the spear).")); ?></p>
    <p><?php echo $this->purify($this->translate("During the Gosamen war (1083-1087), he fought alongside his brothers
        against the Kiyohata clan, under the imperial banner (as the Minamoto
        where often asked to do). It is with one of his brothers, Yoshiie, that
        he besieged Kanazawa castle; the siege lasted one year and was successful.")); ?></p>
    <p><?php echo $this->purify($this->translate("It is during this siege that the two brothers were said to have dissected
        bodies of fallen enemy soldiers in order to study their anatomical structures.
        This practice was said to have helped Yoshimitsu in perfecting his unarmed
        martial art.")); ?></p>
    <p><?php echo $this->purify($this->translate("Because of his military prowess Yoshimitsu was made lord of Kai by
        the Emperor. One of Yoshimitsu's son, Minamoto Yoshikiyo, moved to Takeda
        village in the domain of Kai (present day Yamanashi prefecture) and took
        the name Takeda Yoshikiyo. He later succeded his father as lord of Kai.
        And so the Takeda clan was born.")); ?></p>

    <div class="clear"></div>

    <img src='/Images/History/ShingenTakeda.jpg' alt='Shingen Takeda' />
    <p><strong>Shingen Takeda</strong><?php echo $this->purify($this->translate(", born in 1521 in the city of Kofu, became Daimyo
        of Kai in 1541 when he deposed his father. He was ambitious, a brilliant
        strategist and a formidable leader; his political savvy, however, did
        not measure up to his military might. He was involved in numerous albeit
        fruitless encounters with the Hojo, Imagawa, Tokugawa and Oda clans.")); ?></p>
    <p><?php echo $this->purify($this->translate("But his most intense rivalry was with Uesugi Kenshin, Daimyo of Echigo.
        They confronted each other five times at Kawanakajima. The fourth battle
        is the most memorable and among the most famous in japanese history.")); ?></p>
    <p><?php echo $this->purify($this->translate("Through the years they developed great respect for each other as exemplified
        by this true story:")); ?></p>
    <p><?php echo $this->purify($this->translate("Salt was an important commodity in Japan especially in the mountainous
        areas such as Kai where it was difficult to obtain. Several of Takeda's
        enemies had decided to blockade the import of salt to Kai. When he heard
        of this Uesugi decided to send salt to Takeda saying that he did not want
        his enemy vanquished by a salt blockade but through Yumi-Ya (military
        confrontation). In appreciation Takeda presented Uesugi with a now famous
        blade the Kou-no-Tachi.")); ?></p>
    <img src='/Images/History/ShingenTakeda2.jpg' alt='Shingen Takeda repells an attack' />
    <p><em><?php echo $this->purify($this->translate("See
        here a statue erected at the site where Shingen Takeda repelled the attack
        of Uesugi Kenshin with his tessen at the 4th battle of Kawanakajima 10
        Sept 1561.")); ?></em></p>
    <p><?php echo $this->purify($this->translate("Years later, upon hearing of Shingen's death, Uesugi is said to have
        wept at the loss of his 'best enemy'.")); ?></p>
    <p><?php echo $this->purify($this->translate("During his reign Shingen built Yogai castle in Kofu. He resided on
        the shores of lake Suwa strategically located and within view of mount
        Fuji.")); ?></p>
    <p><?php echo $this->purify($this->translate("It is while reading Sun Tzu`s Art of War that he found what would become
        his famous Furin Kazan:")); ?></p>
    <p class='nomargin'><em><?php echo $this->purify($this->translate("Quick as the wind,")); ?></em></p>
    <p class='nomargin'><em><?php echo $this->purify($this->translate("Peaceful as the forest,")); ?></em></p>
    <p class='nomargin'><em><?php echo $this->purify($this->translate("Overwhelming as fire,")); ?></em></p>
    <p class='nomargin'><em><?php echo $this->purify($this->translate("As immovable as a mountain")); ?></em></p>
    <p><?php echo $this->purify($this->translate("A sniper's bullet put an end to his life during the siege of Noda castle
        in april of 1573, as he approached enemy lines to listen to a defender
        playing his flute. His death was kept a secret for two years and the leadership
        of the clan was assumed by his son Katsuyori. The celebrated japanese
        movie director, Kurosawa, made this incident the subject of a remarkable
        film: Kagemusha. In february of 1574, in accordance with Shingen's last
        will, Kunitsugo Takeda, Shingen's nephew, was welcomed to Aizu by Daimyo
        Moriuji Ashina an old friend of Shingen.")); ?></p>
    <img src='/Images/History/NagashinoValley.jpg' alt='Nagashino Valley' />
    <p><?php echo $this->purify($this->translate("Katsuyori
        besieged the castle of Nagashino in june 1575 against an alliance formed
        by Oda Nobugana. On the morning of june 29, 1575 the famed cavalry of
        the Takeda clan charged in the direction of the Rengogawa river which
        had been laden with ropes by the defenders. This slowed them down considerably,
        and they where now easy targets for the 3,000 arquebusiers that where
        waiting for them. They were slaughtered.")); ?></p>
    <p><?php echo $this->purify($this->translate("Katsuyori retreated to Kai. The combined forces of Oda and Tokugawa
        invaded Kai and defeated him in 1582. Katsuyori committed seppuku. This
        was the end of the Takeda clan as a military force.")); ?></p>
    <div class="clear">&nbsp;</div>


    <h4><?php echo $this->purify($this->translate("6 generations")); ?></h4>
    <p><?php echo $this->purify($this->translate("Hoshina Masayuki becomes Lord of Aizu in 1643 (Grandson of Shogun Tokugawa
        Ieyasu, he adopted the name Matsudaira in 1696. Matsudaira was Tokugawa
        Ieyasu's original family name. The interest of mentionning this paticular
        Daimyo in the lineage is that he became quite an enthousiast and practitionner
        and was a major factor in the survival and development of the art.)")); ?></p>


    <h4><?php echo $this->purify($this->translate("4 generations")); ?></h4>

    <p> Soemon Takeda</p>
    <p> Sokichi Takeda</p>
    <img src='/Images/History/TakedaSokaku.jpg' alt='Takeda Sokaku'>
    <img src='/Images/History/TakedaTokimune.jpg' alt='Takeda Tokimune'>
    <img src='/Images/History/MatsudairaKatamori.jpg' alt='Matsudaira Katamori'>
    <div class="clear">&nbsp;</div>

    <p><?php echo $this->purify($this->translate("Aizu-Wakamatsu is a town situated in the west of Fukushima Prefecture.
        It faces Lake Inawashiro. The city center was initiated by the construction
        of a castle by Ashina Family. The Ashina family had been rewarded and
        given the Aizu fief for helping the Minamoto establish the first military
        government of Japan in 1192.")); ?></p>
    <p><?php echo $this->purify($this->translate("The mansion constructed by Ashina Naonari in the first year of Shitoku
        Era (1333) would be the origin of the castle, completed in 1384 it would
        be known as Kurokawa Castle. In 1589 Date Masamune took the castle, but
        his reign was short lived; Gamo Ujisato, a Hideyoshi retainer, overtook
        it in the 18th year of Tensho Era (1591) to rename it Tsuruga Castle.
        In 1643 Hoshina Masayuki was appointed Governer of Aizu by his brother,
        Shogun Iemitsu. His name was later changed to Matsudaira. The Matsudaira
        ruled Aizu till the defeat of the clan in September of 1868.")); ?></p>
    <img src='/Images/History/NishinkanSchool.jpg' alt='Nishinkan's Aizu Martial arts school'>
    <p><?php echo $this->purify($this->translate("In october of 1799 the Nishinkan, Aizu Martial arts school, was completed.
        The Nisshinkan school was founded by Genko Tanaka. In 1874, all the buildings
        including the main donjon were destroyed but in September 1965, it was
        restored to the initial state.")); ?></p>
    <p><?php echo $this->purify($this->translate("Tenshyukaku is the main tower of a whole castle compound and was formed
        originally from a watchtower built above the habitation during the civil
        war period of Sengoku (1467-1603). It has become then more and more solid
        serving as well as a defense function. During Edo period it was considered
        a symbol of the local daimyo's authority and became more decorative. Beginning
        from a simple fort or a camp in the civil war period, it became a residence
        and an administration office during the Edo period (1603-1867). It served
        as well as a defense point by adding a donjon to its center. Those compound
        buildings as a whole are called 'Jokaku'.")); ?></p>
    <p><?php echo $this->purify($this->translate("In 1868, after a defeat in the battle of Toba-Fushimi, the order was
        given to subjugate the daimyo Matsudaira Katamori. So, the government
        attacked Aizu, Matsudaira opposed it by forming an alliance with about
        thirty feudal clans of Tohoku Region. They had resisted by holding Wakamatsu
        Castle even after Edo Castle had surrendered but finally capitulated in
        September after six months of fierce fighting. The sacrifice of the Boy's
        Corps of Nihonmatsu and the famous collective suicide of the 'White Tiger
        Regiment'(Byakko-tai), both formed by boys not older than 17, occurred
        at that moment.")); ?></p>
    <div class="clear"></div>


    <img src='/Images/History/TokugawaIeyasu.jpg' alt='Tokugawa Ieyasu'>
    <p><strong><?php echo $this->purify($this->translate("The Edo era")); ?></strong></p>
    <p>
        <strong><?php echo $this->purify($this->translate("The beginning of the Edo era")); ?></strong>
        <?php echo $this->purify($this->translate("Three men in japanese history are known as 'The three unifiers' they are: ")); ?>
    </p>
    <ul>
        <li>Oda Nobunaga (1534-82)</li>
        <li>Toyotomi Hideyoshi (1536-98)</li>
        <li>Tokugawa Ieyasu (1542-1616)</li>
    </ul>
    <p><?php echo $this->purify($this->translate("The events that brought about the end of the Takeda clan as a military
        force where described in the biography of Shingen Takeda. This was the
        era of the Warring States and of course many clans like the Takeda where
        subdued, many formed alliances but few held the reins of power.")); ?></p>
    <p><?php echo $this->purify($this->translate("After the dust had settled over all the battlefields it would be Oda
        Nobugana who would be military leader of Japan but he never held the tittle
        of Shogun. Save for a few reluctant Daimyos Japan was practically unified
        in 1582 when he was assassinated at the Honnoji temple by one of his generals,
        Akechi Mitsuhide. The latter proclaimed himself Shogun; but his reign
        would last only 13 days. Upon hearing of Oda's death Toyotomi Hideyoshi,
        one of Oda's most faithful generals, killed Mitsuhide.")); ?></p>
    <img src='/Images/History/HideyoshiToyotomi.jpg' alt='Hideyoshi Toyotomi'>
    <p><?php echo $this->purify($this->translate("Hideyoshi succeeded Oda but like him was not Shogun, he was a man of modest origin
        but a fierce warrior so the other important Daimyos did not oppose him.
        He decided that from then on the tittle of Shogun would be transmitted
        trough lineage to insure stability. He designated his son to be the first
        of a lineage and thus had is five principal generals (among which was
        Tokugawa) swear that if anything should happen to him his son Hideyori
        would be Shogun, they all agreed. In 1587 Hideyoshi banned the possession
        of weapons by commoners, another element to insure stability of the land
        and of course his own. But his ambitions took him beyond the frontiers
        of Japan and he decided to invade Korea. It was a fiasco, and he died
        there of disease in 1598.")); ?></p>
    <p><?php echo $this->purify($this->translate("Tokugawa saw the opportunity: he would be Shogun. Not respecting the
        promise he had made to Hideyoshi meant little to him. He was opposed in
        this decision by Ishida Mitsunari, a faithful Hideyoshi retainer. They
        both made alliances, and their opposing views were finally settled at
        the battle of Sekigahara, on October 21 1600. Tokugawa, of course, was
        the victor there. In 1615, in order to eliminate the true inheritor of
        the tittle of Shogun, he traitorously invaded the fortress of Osaka, where
        Hideyori Toyotomi had taken refuge with a few faithful retainers. They
        where subdued and Hideyori committed seppuku.")); ?></p>
    <p><?php echo $this->purify($this->translate("Nobody thereafter dared oppose him and to insure the loyalty of his
        Daimyos he instituted, among other measures, the Sankin Kotai, a law stipulating
        that the Daimyos had to spend every other year in Edo and when they were
        not in Edo they had to leave behind a member of their family; a concubine,
        a child etc. It was blackmail, but it worked. The Edo period, which lasted
        for over 250, years was one of peace and prosperity.")); ?></p>
    <p><?php echo $this->purify($this->translate("It was also one of isolation for Japan; the policy of sakoku (closed
        nation policy) having been implemented. Save for the Dutch who where allowed
        to reside and trade on the very small Deshima island near the port facilities
        of Nagasaki, no foreigners or even elements of foreign culture where allowed
        to permeate japanese society.")); ?></p>

    <p><?php echo $this->purify($this->translate("It was however for the warrior class a period of idleness, and Tokugawa
        drew up the Buke Sho Hatto. It gave Samurai 13 guides on how a warrior
        should live during peace time. To insure that the skills developed during
        the past centuries would not be lost, many decided to pass them on in
        an organized fashion. It was in this period that most of the Koryu were
        formally developed.")); ?></p>
    <h4><?php echo $this->purify($this->translate("The end of the Edo era")); ?></h4>
    <p><?php echo $this->purify($this->translate("Aside from the natural decay that is to be expected of a regime that
        has been in power for over two hundred years, two series of events triggered
        the downfall of the Tokugawa regime. There where internal discords and
        also the expansionist views of the western world who had wanted Japan
        open to trade for a long time.")); ?></p>
    <p><?php echo $this->purify($this->translate("Among the activities the high ranking but idle samurai did, was the
        study of japanese culture at the School of National Learning. Scholars
        from this school were called kokugakushu and they excluded from their
        studies anything that was not strictly Japanese. One of those samurai,
        Takayama Hikokuro, was a strong proponent of the idea that the Emperor
        was not getting the respect he deserved and that he should be head of
        state.")); ?></p>
    <p><?php echo $this->purify($this->translate("Of course that noble idea was very pleasing to the clans that had been
        on the loosing side at Sekigahara a few centuries before, they had always
        been kept away from the reins of power and they resented the Tokugawa
        with a passion. The Satsuma and Chosu where such clans, they where powerful
        but isolated politically even though they shared a hatred for the Tokugawa.")); ?></p>
    <p><?php echo $this->purify($this->translate("In the first half of the 19th century the British had strongholds in
        China and this was known to the Tokugawa government. The japanese leaders
        where also aware of the military strength of the western countries and
        that in order to pursue their politic of sakoku Japan was to be stongly
        united.")); ?></p>
    <p><?php echo $this->purify($this->translate("On the other side of the Pacific a high ranking american naval officer,
        Alfred T. Mahan, convinced President Fillmore that it was essential for
        the United States to establish, forcibly if necessary, diplomatic relations
        with Japan in order to have access to its ports. President Fillmore dispatched
        for the mission Commodore Matthew Perry.")); ?></p>
    <p><?php echo $this->purify($this->translate("Perry arrived with his four 'black ships' in the bay of Edo on the
        8th of July 1853 with a proposition destined to the Emperor. It stipulated
        that Japan was to open its ports to foreign trade. It that was more an
        ultimatum than a diplomatic endeavor. Perry said he would be back in the
        spring of 1854 for the response.")); ?></p>
    <p><?php echo $this->purify($this->translate("Shogun Iesada Tokugawa needed the support of the provincial Daimyos
        in order to have strong negotiating powers. He, of course, did not get
        it.")); ?></p>
    <p><?php echo $this->purify($this->translate("When Perry came back in February of 1854 Tokugawa had no choice but
        to sign the Treaty of Kanagawa which gave foreigners access to the ports
        of Shimoda and Hakodate; it also stipulated that an american council was
        to be in residence in Shimoda. The council, Townsend Harris, arrived in
        1856.")); ?></p>
    <img src='/Images/History/CommodorePerry.jpg' alt='Commodore Perry' />
    <p><?php echo $this->purify($this->translate("In 1858 Tokugawa Iesada died without an heir. The Roju (head of the Shogun's
        council) and theTozama (the Provincial Daimyos) had opposing views on
        who was to succeed. The Roju appointed Ii Naotsuke as counselor to try
        and resolve the conflict. This was futile; on the 24th of March 1860 he
        was assassinated by a group of samurais who would be the precursors of
        the SHISHI, an organization devoted to the expulsion and if necessary
        brutal assassination of foreigners and the reinstatement of the Emperor.")); ?></p>
    <p><?php echo $this->purify($this->translate("Saigo Takamori (not related to Tanomo Saigo), an important retainer and
        diplomat of the Satsuma clan of the island of Kyushu, was of course in favor
        of the SHISHI's actions.  But their brutality infuriated the foreigners and
        Takamori and the Tozama knew they could not overthrow the Tokugawa regime
        without foreign help.  So the SHISHI were eliminated.")); ?></p>

    <img src='/Images/History/ChosuArtillery.jpg' alt='Chosu Artillery'>
    <img src='/Images/History/EmperorMeiji.jpg' alt='Emperor Meiji'>

    <p><?php echo $this->purify($this->translate("By 1866 the Satsuma and the Choshu clans had decided to form an alliance
        and by 1868 under the military command of Prince Arisugawa, armed with modern
        weapons and dressed like their occidental allies, they formed with other clans
        a formidable army.  The clans who opposed them  (the Aizu clan among others)
        where no match and by the fall of 1868 the Boshin civil war was over and
        Emperor Meiji was restored to power.")); ?></p>
    <p><?php echo $this->purify($this->translate("The treaty, putting an end to the civil war the 'Tosa Settlement', still
       left Tokugawa with some influence.  This infuriated the Satsuma and Chosu clans
       who under Takamori's leadership rebelled against the Emperor they helped
       reinstate.  In the end Prince Arisugawa besieged the castle in Satsuma in
       1877, that put an end to the Satsuma rebellion.  Saigo Takamori received a
       gunshot wound to the lower abdomen and so he would not be taken prisoner was
       beheaded (quite probably at his own request) by one of his own retainers on
       24 September 1877.  This would be the last battle in which samurai would
       participate.")); ?></p>
</div>
