<?php
    $sidebarmenu =  $this->partial('partial/daitoryusubmenu.phtml', array('submenu' => $this->submenu));
    $this->placeholder('sidebarmenu')->set($sidebarmenu);
?>

<h2><?php echo $this->purify($this->translate("Brief Background of Russel Haskin")); ?></h2>
<p><?php echo $this->purify($this->translate("Born in 1971, Russel's interest with the martial arts started with
            Matsubayashi-ryu (Shorin-ryu) Karate, which he began studying with
            Sensei Edward Erler in Albuquerque, New Mexico at age twelve. He was
            promoted to Nidan in 1992. After graduating from the University of
            Colorado at Boulder with a degree in International Affairs in 1994
            he spent one year teaching children's Karate classes in Albuquerque
            before moving to Japan for work in 1996. After arriving in Japan,
            Russel began studying Daito-ryu Aiki Jujitsu under the Hakuho Kai
            with Sensei Okabayashi Shogen. He presently holds the rank of Sandan,
            and has been actively involved in supporting Sensei Okabayashi in
            the reformation of the Hakuho Kai into Hakuho-ryu Aiki Budo. ")); ?></p>
<p><?php echo $this->purify($this->translate("Russel returned to the United States in 2002 to pursue a graduate
            degree at the University of Michigan in Ann Arbor. Despite a busy
            study schedule he leads class every Friday from 6-9 pm at the White
            Oak dojo; which is owned and operated by Sensei Dan Sharp. In addition
            to teaching at the White Oak dojo Russel also teaches seminars for
            Sensei Deric Wilkin's Hakuho-ryu group at Oakland College and James
            Mullin's Hakuho-ryu club in Harrisburg, PA.")); ?></p>
<h2><?php echo $this->purify($this->translate("The Importance of Body Movement in Hakuho-ryu")); ?></h2>
<p><?php echo $this->purify($this->translate("This was my second visit to Montreal, and I was very impressed by
            the dedication everyone exhibited in learning Hakuho-ryu. It was obvious
            that many students were actively practicing the principles covered
            during my last visit, and I truly appreciate everyone's enthusiasm
            for Hakuho-ryu. It is my sincere hope that last weekend's seminars
            will assist everyone in learning this wonderful art.")); ?></p>
<p><?php echo $this->purify($this->translate("The major theme of last weekend's seminars was the importance of
            body movements in Hakuho-ryu. Hakuho-ryu focuses on developing body
            movements that recreate the movements of the masters who originally
            created the koryu arts of Japan. Developing these body movements not
            only provides students with a deeper understanding of the waza, or
            techniques, but also accelerates progress in acquiring proficiency
            with them.")); ?></p>
<p><?php echo $this->purify($this->translate("The 'Ii Ro Ha' and other exercises covered in the seminars were
            created by Okabayashi Sensei to help students develop proper body
            movements. Sometimes, however, it is difficult to understand whether
            or not one is performing these exercises correctly. During last weekend's
            seminar we covered some methods to help students overcome this problem.
            By creatively utilizing uke, students can receive feedback regarding
            their performance of the body movement exercises. This feedback should
            provide students with a guide to improving their execution of the
            exercises, and of course, their body movements.")); ?></p>
<p><?php echo $this->purify($this->translate("In addition to covering methods for checking the body movement exercises,
            we covered applications of the 'Ii Ro Ha' and Aiki Kempo exercises
            in the Shoden waza. By using techniques from Ikkajyo, Nikajyo, and
            Sankajyo to illustrate the connection between the techniques and the
            Aiki Kempo / 'Ii Ro Ha' exercises, I hope students were able to gain
            a better sense of how these areas can be used to improve their waza.")); ?></p>
<p><?php echo $this->purify($this->translate("Knowing the form of the techniques is only the beginning. To polish
            and develop these techniques to their highest level requires an understanding
            of the body movements of the masters who originally created them.
            Gaining this insight is a central concept of Hakuho-ryu, and a major
            purpose for practicing the 'Ii Ro Ha' body movements as well as the
            Aiki Kempo exercises. I hope the past weekend's seminars were helpful
            in providing every one with a better understanding of the importance
            of these areas in Hakuho-ryu, as well as some concrete methods for
            furthering one's study of the art.")); ?></p>