<?php
    $sidebarmenu =  $this->partial('partial/daitoryusubmenu.phtml', array('submenu' => $this->submenu));
    $this->placeholder('sidebarmenu')->set($sidebarmenu);
?>

<div id="interview">
<img src='/Images/Articles/OkabayashiSensei.jpg'>
<h2><?php echo $this->purify($this->translate("Interview with Okabayashi Sensei, founder and headmaster of Daito
              Ryu Hakuho Kai, and Rod Ulher as interpreter.")); ?></h2>
<p><?php echo $this->purify($this->translate("(We would like to dearly thank Okabayashi Sensei and Rod Uhler
                for taking the time to make this interview with us) This interview
                is for viewing only. It may not be reproduced or reused in any
                other public forum or medium without the proper consent and authorisation
                of the Koryukan Dojo and the Hakuho Kai.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Sensei when and where were you born?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I was born on June 27, 1949 in Ashia City, Japan")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("When did you first get involeved in martial arts?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I started training in Shito Ryu Karate when I was about
                15 years olds, and trained in that style for about 6 years.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("When did you begin training in Daito Ryu Aiki Jujutsu?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I was about 21 years old when I started training with
                Takuma Hisa Sensei. So it was in 1970.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Why did you stop your karate training and how did you
                begin your training in Daito Ryu?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("There was an incident I had with some a Yakuza fellow.
                I was out one night with my girlfriend, and he started being rude
                to her. I intervened and asked him to stop, after which he became
                aggressive and attacked me with a bokuto. Since I practiced karate,
                I was quiet strong with my fists and knew I could make a serious
                injury if I punched but I did not want to hurt him badly, so all
                I could do is block the strikes of the stick with my arms. Finally
                he gave up and left me alone. However, after this fight my arms
                were swollen and hurting for two months. After this incident I
                thought hard to myself, what if that was a sword and not a stick
                I was attacked with, I would have lost my arms. So I began to
                search for a martial art that would teach me how to defeat the
                sword. After about a year of looking for a school I came across
                Hisa Takuma Sensei's group, I found the things they were practicing
                very interesting, Hisa Sensei had traditional technique so I asked
                him if I could study under him. He accepted me and so I began
                my training.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("How long did you train with Hisa Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I trained under him until the late seventies, up to
                the point when Hisa Sensei became frail and his son asked him
                to move to Tokyo so he could take care of him.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("How was your training with Hisa Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("With time Hisa Sensei became frail and he could not
                move very well. So he would usually teach by speaking and explaining
                how to do the movements, and demonstrating them slowly. Senior
                students of Hisa Sensei's and me came together and formed what
                is now know as the Takumakai, and practiced the techniques, working
                them out under Hisa Sensei's direction. The training was good
                and we worked hard. At the same time I felt there was something
                missing in the movements, there was some element that wasn't there.
                I endured these feelings and continued my training. After this
                period Hisa Sensei moved to Tokyo upon request of his son. So
                his son would be able to take care of him. When this happened
                I was going to quit my training. So I went to see Hisa Sensei
                to ask him his permission to quit. When I told him of my feelings,
                he told me 'no, you must continue to practice, I will introduce
                you to a very good teacher', and wrote me a letter of recommendation
                to go see Takeda Tokimune Sensei in Hokkaido.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("When did you receive your kyoju dairi from Hisa Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I received it in 1976.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("So after the recommendation from Hisa Sensei, you went
                to train with Takeda Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("That's correct. I went to Abashiri, Hokkaido to learn
                from Takeda Sensei. From him at first I learned basic techniques,
                the shoden. The Takumakai did not have these basic ones; they
                practiced more advanced waza.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("When did you first meet Takeda Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("Twenty five years ago, so it must have been 1977.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("So at that time you were part of the Takumakai?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("That's correct. Because I went with to study under Soke
                (Takeda Tokimune Sensei) with Hisa Sensei's recommendation, in
                Japanese thinking it was as if I was learning from both teachers
                at the same time. I took the shoden waza and brought them back
                to the Takumakai.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("How was your training with Takeda Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I was in pretty fit shape at that time because I did
                a lot of skiing and played a lot of soccer. Although feeling strong,
                I put myself on a 100-day program before going to see Soke (Takeda
                Sensei) to prepare myself for training with him. When I went to
                see him, I was fortunate because Soke quit his work right before
                I got there. We would have one on one training in the morning,
                from 5 A.m. to 8 A.m., then a break until lunch, more one on one
                training after lunch until the evening. And then there was an
                evening class with other students. The first morning I came to
                the dojo at 5, and Soke was already there, so the next day I decided
                to come 15 minutes earlier, at 4:45, to be there before Takeda
                Sensei. The following day, I came to the dojo at 4:45 and Soke
                was already there. So, next morning I showed up at 4:15, and getting
                there before Soke I felt some pride about this. However, the next
                day, I came at 4:15 and Soke was there before me again. I did
                not know the reason for this, but this continued to go on until
                we started training at 3 A.m. At this point, Takeda Sensei's wife
                came out and said to me, 'You can't come into the dojo before
                Soke, he needs his time to train and it is the only time he can
                train by himself before teaching.'")); ?></p>
<p><?php echo $this->purify($this->translate("When training with Soke, I was never allowed to throw or apply
                a technique on him, I was always the uke in our one on one training.
                Takeda Sensei taught me by doing the techniques on me over and
                over again. This was very hard on me at first, can you be uke
                for 1 hour? One on one? But it was 3 hours in the morning and
                more after lunch! In the evening Soke had a class with other students,
                and I got to practice and apply techniques on others that I learned
                during the day with Soke.")); ?></p>
<p><?php echo $this->purify($this->translate("After the third day with Takeda Sensei, I started to feel the
                toll of the training, because it was so severe since I was always
                the uke. But although growing quiet weary, I decided I was there
                to train and persevered, and in a short time I got used to this
                kind of training. Practicing with Soke, I was given permission
                to teach the Takumakai up to the nikajo level, sixty techniques.")); ?></p>
<p><?php echo $this->purify($this->translate("At the time we were about 15 students at Soke's dojo, some of
                the known names being: Arisawa Sensei, Kato Sensei, Saito Sensei,
                the sempai was Akimoto Sensei who passed away at the age of 85.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("How many years did you train with Takeda Tokimune Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("13 years.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Sensei, you also learned Ono Ha Itto Ryu from Takeda Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("That's correct. I was one of only six people to be taught
                Itto Ryu by Soke. He chose to teach it only to people with a good
                heart, because through kenjutsu you can better understand jujutsu.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("When did you receive your certificates from Soke?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I recieved the shihan license in Daito Ryu and menkyo
                in Ono Ha Itto Ryu in 1985 from Takeda Sensei.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Sensei how was the Hakuho Kai born?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("When training with Hisa Sensei I felt that there was
                older body movement involved behind the techniques. And when training
                with Soke, I saw that he absolutely did not do any kind of turning
                and always moved in one line, many of his students were making
                turns and circles and did not do the techniques how Soke would
                do them. For example many would jump, or rise into ippon dori
                instead of releasing (Sensei demonstrates). From watching Soke
                I knew this was not correct, I followed closely how Takeda Sensei
                would move and researched the techniques. At the time I was with
                the Takumakai and taught these things to my own branch dojo. With
                time it became a difficult situation because other people were
                doing and teaching techniques in a different way, and did not
                have the same idea. Even before Takeda Sensei passed away, there
                were already disputes about who will be the next Soke, and about
                this license and that license. Takeda Sensei did not want to have
                any part of this and did not want me involved in it either. He
                told me to stay out of all the politics, and told me to go on
                my own and not stay with an organization. He wanted me teach the
                techniques he taught me. With his encouragement I decided to form
                the Hakuho Kai.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Sensei how did you research the techniques and develop
                your method of teaching?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("I watched very closely how Soke moved, he was always
                moving in hitoemi, one line. I looked at old paintings of the
                bushi, their bodies were also always partrayed as being in a hitoemi
                position because that is how the bushi moved. I read old history
                texts about life in old Japan and how things worked back them.
                Across all of this I did not find anything in particular, but
                there were hints here and there. Then, when researching the techniques,
                we had pictures (Asahi News pictures taken by Hisa Takuma when
                Takeda Sokaku was teaching there) of the beginning of a technique
                and the end of a technique, but could not make certain techniques
                work. I asked myself why have a technique that doesn't work? So
                by applying my knowledge from Soke and my research, applying hitoemi
                and gravity principles I could make those techniques effective
                and efficient.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Sensei, what does 'Hakuho Kai' mean, and why did you chose
                this name?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("Translated 'Hakuho' means 'white phoenix'. You see in
                Japan's history there were a lot of different eras, like the 'Edo'
                era, the 'Meiji' era and so on.... If you go back through history,
                there was an era called 'Hakuho'. It was a time when the Japanese
                decided to stop outside influence from coming into Japan, it was
                an era when Japanese were protecting Japanese culture from outside
                influence. I want to preserve Daito Ryu in it's traditional form
                and keep the old movements of the bushi behind the techniques,
                and to not let modern body movement influence it. This is why
                I chose the name Hakuho Kai.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("How was Hisa Sensei as a person?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("His was a very interesting person. He liked to try many
                news things. For example learned how to fly and airplane, and
                played golf when it was not as popular as now. He enjoyed life
                and was a very good, kind man.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("How was Takeda Tokimune Sensei as a person?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("He had a very good heart. After the war, Soke was a
                police officer and later became a detective. He was a very suspicious
                person, always suspicious of every one so this must have helped
                him being a detective. He probably inherited some of these traits
                from his father, Takeda Sokaku.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Did Soke speak a lot about his father? Tell many stories?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("Soke never called his father by saying 'father', he
                always refered to him as Takeda Sokaku. He did not really think
                of him as a father. When Soke was 10, 11 years old, Takeda Sokaku
                was approaching 70 years of age. Soke learned kenjutsu from his
                mother until 5 years old, and after the age of 5 he learned from
                his father. Takeda Sokaku trained him very hard, he did not have
                techniques to teach specifically to children. He would have Soke
                attack him with a sword, he would disarm Tokimune and the sword
                would go flying into the snow. So at 5 years old Soke would have
                to go searching through the snow with his bare hands for the sword,
                pick it up and attack his father. Once again the sword would fly
                into the snow, and it went on again and again. So this is just
                and example of how Takeda Sokaku would treat and train his son.
                It was difficult for Soke to think of him as his father. One day
                Takeda Sokaku was sleeping, and Soke wanted to put a cover over
                him to keep him warm. Sokaku, always being in a state of awerness,
                even when sleeping, grabbed his dagger and went to stab Soke in
                heart just as Soke was about to put the cover over Sokaku. Soke
                was barely quick enough to move to the side, got off the line
                and the dagger that was going for his heart stabbed him in the
                shoulder. Afterwards Takeda Sokaku scolded his son severely. Saying:
                ' What kind of a fool are you?! You should never carelessly come
                up one someone by surprise, it is your fault that you were stabbed;
                if you would have been aware I would not have cut you!' That's
                the kind of man Takeda Sokaku was so it must have had an effect
                on Soke, so he did not feel as Sokaku being his father.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Did Soke use dan rankings when teaching?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("Yes, Takeda Sensei used the dan ranking system that
                originally comes from judo. He a gave out other licenses like
                the menkyo and shihan license I have. Takeda Sensei also gave
                two kyuoju dairi, one to Suzuki Sensei and Minamo Sensei, who
                have both passed away. When giving dan grades, in reality Soke
                never gave past fifth dan.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Sensei are dan rankings used in Hakuho Kai?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("That's correct, we use the dan ranking system. It is
                important to note that permission to teach is not the same thing
                as a rank. In Hakuho Kai one must have a good heart and good intentions
                to have permission to teach.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("How many Hakuho Kai dojo are there Sensei?")); ?></strong></p>
<p><?php echo $this->purify($this->translate("Let's see, there are three in Italy, one in England,
                three in the U.S., one in Canada, and fourteen in Japan, in the
                Osaka and Fukuoka areas. So that's four in North America, four
                in Europe, and fourteen in Japan. Making that 22 dojo and about
                420 people in all. I am happy all of our members are good normal
                people and have the right samurai spirit.")); ?></p>

<p class="question"><strong><?php echo $this->purify($this->translate("Thank you very much Sensei, and thank you very much Rod
                for doing a great job at translating.")); ?></strong></p>
<p><?php echo $this->purify($this->translate("Thank you.")); ?></p>


<p><?php echo $this->purify($this->translate("By now it was getting time to go and show Okabayashi Sensei
                and Rod a little bit of Montreal. We thanked him and Rod Ulher,
                his assistant and interpreter dearly for their time and set on
                our way.")); ?></p>

<p><?php echo $this->purify($this->translate("This interview is for viewing only. It may not be reproduced
                or reused in any other public forum or medium without the proper
                consent and authorisation of the Koryukan Dojo and the Hakuho
                Kai.")); ?></p>

</div>