
<h2><?php echo $this->purify($this->translate("Children/family Classes*: ")); ?></h2>
<p><?php echo $this->purify($this->translate("Aiki jujutsu is art based on self defence and therefore a very peaceful.
                The strikes that are used have only for goal to destabilize, to distract the adversary to let us control and attack
                or to simply avoid or get rid of the aggressor to put an end to the attack.")); ?></p>
<p><?php echo $this->purify($this->translate("It is therefore difficult for children to use Aiki jujutsu in an aggressive way or to attack another child. We utilize the
                strength, the speed and the body movement of the attacker to apply our techniques. No attack, no Aiki.")); ?></p>
<p><?php echo $this->purify($this->translate("An excellent form of self defence, which demands little or no strength, Aiki jujutsu is perfect for children. By practicing
                regularly the basic movements as well as the falls and rolls, children become more efficient in their techniques while
                minimizing their risk of injury.")); ?></p>
<p><?php echo $this->purify($this->translate("Aiki Jujutsu develops flexibility, strength, coordination, balance, confidence and concentration in children as young as 5
                or 6 years of age and all of this in a fun environment. It also favours discipline, respect of others and self respect as
                well. The belt system promotes advancement and motivates the child to persevere.")); ?></p>
<p><?php echo $this->purify($this->translate("* Our program allows the parent to participate in the class if they desire which can reassure the child and help to
                understand the Dojo rules. The child learns to play with the parent without the parent being the authority figure.
                For the parent it is an excellent initiation to martial arts as well as offering the opportunity to exercise and stretch
                while spending some nice family time on Sunday morning.")); ?></p>
