<h2><?php echo $this->purify($this->translate('Manage Users')); ?></h2>

<table id="userGrid"></table>
<div id="userPager"></div>


<script type="text/javascript">
$(function() {


    jQuery("#userGrid").jqGrid({
        url:'/<?php echo $this->purify($this->lang); ?>/administration/getusers',
        datatype: "json",
        colNames:['id', 'username', 'First Name', 'Last Name', 'Email', 'Status'],
        colModel:[
            {name:'id',index:'id', width:55},
            {name:'username',index:'username', width:55},
            {name:'firstName',index:'firstName', width:55},
            {name:'lastName',index:'lastName', width:55},
            {name:'email',index:'email', width:55},
            {name:'status',index:'status', width:55}
        ],
        caption: "<?php echo $this->purify($this->translate('Users')); ?>",
        navGrid: $('#userPager'),
    });
});
</script>