<?php echo $this->doctype() ?>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Koryukan est la seule &eacute;cole de aiki-jujutsu de style Daito Ruy au Canada. L'aiki-jujutsu est un art martial Japonais" />
    <meta name="keywords" content="Daito Ryu, hakuhoryu, aiki, aikijujutsu, aiki jujutsu, aikibudo, art martial, arts martiaux, aikijujitsu, aiki jujitsu, Ono Ha Itto Ryu, kenjutsu, Aiki Budo kendo Jujutsu" />


    <title>Koryukan</title>
    <?php echo $this->headLink()->appendStylesheet('/css/koryukan.css'); ?>

    <?php
        $config = Zend_Registry::get('config');
        $jQueryFile = $config->jqueryfile;
        $jQueryLightBoxFile = $config->jquerylightboxfile;
    ?>
    <script type="text/javascript" src="/js/<?php echo $jQueryFile; ?>"></script>
    <script type="text/javascript" src="/js/<?php echo $jQueryLightBoxFile; ?>"></script>
    <link rel="stylesheet" type="text/css" href="/css/jquery.lightbox-0.5.css" media="screen" />
</head>
<body>

    <div id="maincontent">
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>