<?php
    echo $this->doctype();

    $config = Zend_Registry::get('config');
    $jQueryFile = $config->jqueryfile;
    $jQueryUITheme = $config->jqueryui->theme;

    $this->headLink()->appendStylesheet('/css/koryukanMembers.css');
    $this->headScript()->appendFile('/js/' . $jQueryFile, 'text/javascript');
    $this->headScript()->appendFile('/js/jquery-ui-1.8.2.custom.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/menu.js', 'text/javascript');

    $this->headScript()->appendFile('/js/grid_i18n/grid.locale-' . $this->lang . '.js', 'text/javascript');
    $this->headScript()->appendFile('/js/jquery.jqGrid.min.js', 'text/javascript');

    $this->headScript()->appendFile('/js/jquery.validate.min.js', 'text/javascript');
    if (0 === strcasecmp($this->lang, 'fr')) {
        $this->headScript()->appendFile('/js/validate_i18n/messages_fr.js', 'text/javascript');
    }

    $this->headLink()->appendStylesheet('/css/jQueryUI/' . $jQueryUITheme . '/jquery-ui-1.8.2.custom.css');
    $this->headLink()->appendStylesheet('/css/ui.jqgrid.css');

?>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Koryukan est la seule &eacute;cole de aiki-jujutsu de style Daito Ruy au Canada. L'aiki-jujutsu est un art martial Japonais" />
    <meta name="keywords" content="Daito Ryu, hakuhoryu, aiki, aikijujutsu, aiki jujutsu, aikibudo, art martial, arts martiaux, aikijujitsu, aiki jujitsu, Ono Ha Itto Ryu, kenjutsu, Aiki Budo kendo Jujutsu" />


    <title>Koryukan</title>

    <?php
        echo $this->headLink();
        echo $this->headScript();
    ?>

</head>
<body class="ui-widget">
    <!-- Page Header -->

    <?php echo $this->partial('header.phtml', array()); ?>

    <div id="page">
        <div id="divmenu">
            <?php echo $this->layout()->menu; ?>
        </div>

        <div id="maincontent">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>

</body>
</html>