<h2><?php echo $this->purify($this->translate('homeHeader')); ?></h2>
<p>
<?php echo $this->purify($this->translate('homePar1')); ?>
</p>

<p>
<?php echo $this->purify($this->translate('homePar2')); ?>
</p>

<p>
<?php echo $this->purify($this->translate('homePar3')); ?>
</p>

<!--
<h2><?php echo $this->purify($this->translate('homeHeader2')); ?></h2>
<p>
<?php echo $this->purify($this->translate('homePar4')); ?>

</p>
 -->