<?php
    echo $this->doctype();

    $config = Zend_Registry::get('config');
    $jQueryFile = $config->jqueryfile;
    $jQueryLightBoxFile = $config->jquerylightboxfile;

    $this->headLink()->appendStylesheet('/css/koryukan.css');
    $this->headScript()->appendFile('/js/' . $jQueryFile, 'text/javascript');
    $this->headScript()->appendFile('/js/' . $jQueryLightBoxFile, 'text/javascript');
    $this->headLink()->appendStylesheet('/css/jquery.lightbox-0.5.css');
?>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Koryukan est la seule &eacute;cole de aiki-jujutsu de style Daito Ruy au Canada. L'aiki-jujutsu est un art martial Japonais" />
    <meta name="keywords" content="Daito Ryu, hakuhoryu, aiki, aikijujutsu, aiki jujutsu, aikibudo, art martial, arts martiaux, aikijujitsu, aiki jujitsu, Ono Ha Itto Ryu, kenjutsu, Aiki Budo kendo Jujutsu" />


    <title>Koryukan - <?php echo $this->purify($this->pageTitle); ?></title>

    <?php
        echo $this->headLink();
        echo $this->headScript();
    ?>

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18247173-1']);
  _gaq.push(['_setDomainName', '.koryukan.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body>

    <!-- Page Header -->
    <?php echo $this->partial('header.phtml', array('pageTitle' => $this->pageTitle)); ?>


    <div id="page">
        <div id="leftsidebar">
            <?php echo $this->partial('sidebar.phtml', array('sideImage' => $this->sideImage,
                'sideImageAlt' => $this->sideImageAlt));?>
        </div>

        <div id="maincontent">
            <?php echo $this->layout()->content ?>
        </div>

        <div id="footer">
            <!-- No footer -->
        </div>
    </div>






</body>
</html>