<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Koryukan est la seule &eacute;cole de aiki-jujutsu de style Daito Ruy au Canada. L'aiki-jujutsu est un art martial Japonais" />
    <meta name="keywords" content="Daito Ryu, hakuhoryu, aiki, aikijujutsu, aiki jujutsu, aikibudo, art martial, arts martiaux, aikijujitsu, aiki jujitsu, Ono Ha Itto Ryu, kenjutsu, Aiki Budo kendo Jujutsu" />


    <title>Koryukan</title>
    <?php echo $this->headLink()->appendStylesheet('/css/koryukan.css'); ?>

    <?php
        $config = Zend_Registry::get('config');
        $jQueryFile = $config->jqueryfile;
        $jQueryLightBoxFile = $config->jquerylightboxfile;
    ?>
    <script type="text/javascript" src="/js/<?php echo $jQueryFile; ?>"></script>
    <script type="text/javascript" src="/js/<?php echo $jQueryLightBoxFile; ?>"></script>
    <link rel="stylesheet" type="text/css" href="/css/jquery.lightbox-0.5.css" media="screen" />
</head>
<body>

    <!-- Page Header -->
    <?php echo $this->partial('header.phtml', array('pageTitle' => $this->pageTitle)); ?>


    <div id="page">
        <div id="leftsidebar">
            <?php echo $this->partial('sidebar.phtml', array('sideImage' => $this->sideImage,
                'sideImageAlt' => $this->sideImageAlt));?>
        </div>

        <div id="maincontent">
            <?php echo $this->layout()->content ?>
        </div>

        <div id="footer">
            <!-- No footer -->
        </div>
    </div>






</body>
</html>