<table class="ImagesTable" cellpadding=5>
    <?php
        foreach ($this->imageSections as $imageSection) {
            $images = $imageSection->getImages();
            $mainImageFileName = $images->getAtIndex(0)->getFileName();

    ?>
        <tr>
            <td>
                 <a href=javascript:OpenImageWindow('<?php echo $mainImageFileName; ?>')>
                    <img src="/Images/Multimedia/<?php echo $mainImageFileName; ?>" />
                </a>
            </td>
            <td>
                <b><?php echo $imageSection->getSectionDate()->toString(Zend_Date::DATES); ?></b><br />
                <?php echo $imageSection->getSectionTitle($this->lang); ?><br />
                <?php
                    foreach ($images as $image) {
                ?>
                        <a href=javascript:OpenImageWindow('<?php echo $image->getFileName();; ?>')><?php echo $image->getDescription($this->lang); ?></a> <br />
                <?php
                    }
                ?>
            </td>
        </tr>
    <?php } ?>
</table>

<?php return; ?>


    <?php foreach ($this->imageSections as $imageSection): ?>
        <tr>
            <td>
                <?php
                    $urlmain = 'montrerphoto/MontrerPhoto/' . $imageSection['SectionMainImage'];
                    $urlmain = url_lang::site($urlmain);
                ?>
                <a href=javascript:OpenImageWindow('<?php echo $urlmain; ?>')>
                    <img border=0 src="/media/Images/Multimedia/<?php echo $ImageSection['SectionSmallImage']; ?>" />
                </a>
            </td>
            <td>
                <b><?php echo $ImageSection['SectionDate']; ?></b><br />
                <?php echo $ImageSection['SectionTitle']; ?><br />

                <?php
                    foreach ($ImageSection['Images'] as $Image):
                        $urlimage = 'montrerphoto/MontrerPhoto/' . $Image['Image'];
                        $urlimage = url_lang::site($urlimage);
                ?>

                    <a href=javascript:OpenImageWindow('<?php echo $urlimage; ?>')><?php echo $Image['Description']; ?></a> <br />
                <?php endforeach ?>
            </td>
        </tr>
    <?php endforeach ?>


