<table class="ImagesTable" cellpadding=5>
    <?php
        foreach ($this->imageSections as $imageSection) {
            $images = $imageSection->getImages();
            $mainImageFileName = $images->getAtIndex(0)->getFileName();
            $purifiedSectionTitle = $this->purify($imageSection->getSectionTitle($this->lang));

    ?>
        <tr>
            <td>
                 <a href="/Images/Multimedia/<?php echo $mainImageFileName; ?>" title="<?php echo $purifiedSectionTitle; ?>">
                    <img src="/Images/Multimedia/<?php echo $mainImageFileName; ?>" />
                </a>
            </td>
            <td>
                <b><?php echo $imageSection->getSectionDate()->toString(Zend_Date::DATES); ?></b><br />
                <?php echo $purifiedSectionTitle; ?><br />
                <?php
                    foreach ($images as $image) {
                        $purifiedDescription = $this->purify($image->getDescription($this->lang));
                ?>
                        <a href="/Images/Multimedia/<?php echo $image->getFileName();?>" title="<?php echo $purifiedDescription; ?>">
                            <?php echo $purifiedDescription; ?>
                        </a>
                        <br />
                <?php
                    }
                ?>
            </td>
        </tr>
    <?php } ?>
</table>


<script type="text/javascript">
$(function() {
    $('table.ImagesTable a').lightBox({
        imageLoading: '/Images/Lightbox/lightbox-ico-loading.gif',
        imageBtnClose: '/Images/Lightbox/lightbox-btn-close.gif',
        imageBtnPrev: '/Images/Lightbox/lightbox-btn-prev.gif',
        imageBtnNext: '/Images/Lightbox/lightbox-btn-next.gif',
        imageBlank: '/Images/Lightbox/lightbox-blank.gif'
       });
});
</script>


<?php return; ?>


    <?php foreach ($this->imageSections as $imageSection): ?>
        <tr>
            <td>
                <?php
                    $urlmain = 'montrerphoto/MontrerPhoto/' . $imageSection['SectionMainImage'];
                    $urlmain = url_lang::site($urlmain);
                ?>
                <a href=javascript:OpenImageWindow('<?php echo $urlmain; ?>') >
                    <img border=0 src="/media/Images/Multimedia/<?php echo $ImageSection['SectionSmallImage']; ?>" />
                </a>
            </td>
            <td>
                <b><?php echo $ImageSection['SectionDate']; ?></b><br />
                <?php echo $ImageSection['SectionTitle']; ?><br />

                <?php
                    foreach ($ImageSection['Images'] as $Image):
                        $urlimage = 'montrerphoto/MontrerPhoto/' . $Image['Image'];
                        $urlimage = url_lang::site($urlimage);
                ?>

                    <a href=javascript:OpenImageWindow('<?php echo $urlimage; ?>')><?php echo $Image['Description']; ?></a> <br />
                <?php endforeach ?>
            </td>
        </tr>
    <?php endforeach ?>


